## Image name: chewie/packet-fuzzer

FROM faucet/test-base:latest

ENV PIP3="pip3 -q --no-cache-dir install --upgrade"

RUN \
  apt-get update && \
  apt-get install -y afl cython3

COPY ./ /chewie-src/
WORKDIR /chewie-src


RUN \
  $PIP3 -r requirements.txt && \
  $PIP3 -r fuzz-requirements.txt && \
  $PIP3 .

VOLUME ["/var/log/chewie/", "/var/log/afl/", "/etc/chewie/", "/var/run/chewie/"]

EXPOSE 6653 9302

CMD ["docker/fuzz_packet.sh"]
