FROM ubuntu:16.04

RUN apt-get update

RUN apt-get update && \
    apt-get install -y python3 python3-pip vim \
        software-properties-common wpasupplicant && \
    add-apt-repository ppa:freeradius/stable-3.0 && \
    apt-get update && \
    apt-get install -y freeradius


COPY ./requirements.txt /tmp/requirements.txt
COPY ./test-requirements.txt /tmp/test-requirements.txt
RUN pip3 install -r /tmp/requirements.txt -r /tmp/test-requirements.txt

CMD /chewie-src/docker/run_integration.sh
