FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y vim

# Install Dependencies
COPY ./requirements.txt /tmp/requirements.txt
COPY ./test-requirements.txt /tmp/test-requirements.txt
RUN pip3 install -r /tmp/requirements.txt -r /tmp/test-requirements.txt

# Set up requirements for Chewie to run tests
COPY ./ /chewie
RUN ln -s /usr/bin/pip3 /usr/bin/pip

# Run Tests
WORKDIR /chewie
CMD ["./run_tests.sh"]
